#include <QtTest>
#include <QCoreApplication>


// add necessary includes here

#include "../src/core/abifsequencetrace.h"

class CutePeaks : public QObject
{
    Q_OBJECT

public:
    CutePeaks();
    ~CutePeaks();

private slots:
    void initTestCase();
    void cleanupTestCase();

    void test_abif();

};

CutePeaks::CutePeaks()
{

}

CutePeaks::~CutePeaks()
{

}

void CutePeaks::initTestCase()
{

}

void CutePeaks::cleanupTestCase()
{

}

void CutePeaks::test_abif()
{
QDir dir = QDir(PROJECT_PATH);
dir.cd("..");
dir.cd("examples");
QString filepath = dir.absoluteFilePath("A_reverse.ab1");
Q_ASSERT (QFile::exists(filepath));

AbifSequenceTrace trace = AbifSequenceTrace(new QFile(filepath));

Q_ASSERT (trace.version() == 101);

Q_ASSERT( trace.sequence().toString() == "TAGGGGCAGCGCCTMACCCTCCGTMTGTGCTGTGACTGCTTGTAGATGGCMTGGCGCGGACGCGGGTGCCGGGCGGGGGTGTGGAATCAACCCACAGCTGCACAGGGCAGGTCTTGGCCAGTTGGCAAAACATCTTGTTGAGGGCAGGGGAGTACGTGCAAGTCACAGACTTGGCTGTCCCAGAATGCAAGAAGCCCAGACGGAAACCGTAGCTGCCCTGGTAGGTTTTCTGGGAAGGGACAGAAGATGACAGGGGCCAGGAGGGGGCTGGTGCAGGGGCCGCCGGTGTAGGAGCTGCTGGTGCAGGGGCCACGCGGGGAGCAGCCTCTGGCATTCTGGGAGCTTCATCTGGACCTGGGTCTTCAGTGAACCATTGTTCAATATCGTCCGGGGACAGCATCATATCATCCATTGCTTGGGACGGCAAGGGGGACAGAACGTTGTTTTCAGGAAGTAGTTTCCATAGGTCTGAAAATGTTTCCTGACTCAGAGGGGGCTCGACGCTAGGATCTGACTGCGGCTCCTCCATAGATCTGAGTCCGGCCGGACTTGTACAGCTCGTCCATGCCGAGAGTGATCCCGGCGGCGGTCACGAACTCCAGCAGGACCATGTGATCGCGCTTCTCGTTGGGGTCTTTGCTCAGGGCGGACTGGGTGCTCAGTAGTGGTTGTCGGGCAGCAGCACGGGGCCGTCGCCGATGGGGGTGTTCTGCTGGTAGTGGTCGGCGAGCTGCACGCTGCCGTCTCGATGTGTGCGATCTTGAAGTTCACCTTGATGCCGTTCTTYKGCTTKTCGG");


}

QTEST_MAIN(CutePeaks)

#include "tst_cutepeaks.moc"
