# Travis-CI build script for sdsl-lite

language: cpp

cache:
  apt: true
  ccache: true

sudo: false

matrix:
  include:
    # ubuntu toolchain does not contain the latest bugfixes for /usr/bin/ld
    - env:
        - MYCC="gcc-8" MYCXX="g++-8" MYBUILD=Debug
        - CXX_FLAGS="-fsanitize=address -fuse-ld=gold"
        - CTEST_EXCLUDE="faust|moby|-im"
      os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'g++-8']

    # ubuntu toolchain does not contain the latest bugfixes for /usr/bin/ld
    - env:
        - MYCC="gcc-8" MYCXX="g++-8" MYBUILD=Debug
        - CXX_FLAGS="-fsanitize=address -fuse-ld=gold"
        - CTEST_EXCLUDE="faust|moby" CTEST_INCLUDE="-im"
      os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'g++-8']

    - env: MYCC="gcc-4.9" MYCXX="g++-4.9" MYBUILD=Release
      os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'g++-4.9']

    - env: MYCC="gcc-5" MYCXX="g++-5" MYBUILD=Release
      os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'g++-5']

    - env: MYCC="gcc-6" MYCXX="g++-6" MYBUILD=Release
      os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'g++-6']

    - env: MYCC="gcc-7" MYCXX="g++-7" MYBUILD=Release
      os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'g++-7']

    - env:
        - MYCC="gcc-7" MYCXX="g++-7" MYBUILD=Release
        - HAS_CEREAL="1"
      os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'g++-7']

    - env:
        - MYCC="gcc-7" MYCXX="g++-7" MYBUILD=Release
        - HEADER_TEST="ON"
      os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'g++-7']

    - env: MYCC="gcc-8" MYCXX="g++-8" MYBUILD=Release
      os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'g++-8']

    - env: MYCC="clang-3.8" MYCXX="clang++-3.8" MYBUILD=Release
      os: linux
      dist: trusty
      addons:
        apt:
          sources: ['llvm-toolchain-precise-3.8', 'ubuntu-toolchain-r-test']
          packages: ['cmake', 'clang-3.8', 'g++-7'] # g++ required for newer libstdc++

    - env: MYCC="clang" MYCXX="clang++" MYBUILD=Release
      os: osx

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ccache ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH" ; fi

before_script:
  - export CXX=$MYCXX
  - export CC=$MYCC
  - $CXX --version
  - cmake --version
  - ccache --version

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir sdsl-lite-build && cd sdsl-lite-build
  - cmake ${TRAVIS_BUILD_DIR} -DCMAKE_BUILD_TYPE=$MYBUILD -DCMAKE_CXX_FLAGS="-Werror -Wno-missing-field-initializers ${CXX_FLAGS}" -DSDSL_CEREAL=$HAS_CEREAL -DSDSL_HEADER_TEST=$HEADER_TEST
  - if [[ $HEADER_TEST == "ON" ]];
    then make sdsl_header_test -k -j 2;
    else make sdsl_test_targets -k -j 2;
         travis_wait 90 sleep infinity & ctest . -j 2 --output-on-failure -E ${CTEST_EXCLUDE} -R ${CTEST_INCLUDE};
         make sdsl_examples -k -j 2;
         make sdsl_tutorials -k -j 2;
    fi

after_script:
  - ccache -s
